name: "Testeo de la aplicación"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: descarge los paquetes de composer
        run: composer install --no--progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Crear .env file
        run:
            cp -env.example .env

      - name: Generate aplication key
        run: php artisan key:generate

      - name: node installation to ubuntu
        run: actions/setup-node@v3
        with:
          node-version: "22"

      - name: instalamos los paquetes de node js
        run: npm install

      - name: compilamos front
        run: npm run build

      - name: Run migrations
        run: php artisan test
